version: "3.9"

networks:
  backend:

services:
  btc-app:
    build:
      context: ./
    container_name: btc-app
    hostname: gses2.app
    networks:
      - backend
    env_file:
      - secrets.env
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./data:/app/data
    entrypoint: npm run start
#  swagger-ui:
#    image: swaggerapi/swagger-ui
#    container_name: swagger_ui_container
#    networks:
#      - backend
#    ports:
#      - "80:80"
##    volumes:
##      - ./doc:/usr/share/nginx/html/doc
#    environment:
#        API_URL: /gses2swagger.yaml

